_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 41
                - 54
                - 55
            "2":
                - 1
                - 41
                - 54
                - 55
            "3":
                - 23
                - 55
            "4": 3.12.7
            "5": 0.18.1
            "8":
                - 3
                - 5
            "12": 0.18.1
            "13": windows-amd64
