vae_gan:
  vae:
    channel_in: 1
    ch: 64
    blocks: (1, 2)
    latent_channels: 3
    num_res_blocks: 8
    norm_type: "bn"
    deep_model: False
    lr: 0.0001
  
  discriminator:
    in_channels: 1
    channel_list: [64, 128, 256]
    lr: 0.000001
  
  loss:
    perceptual_weight: 1.0
    l2_weight: 0.01
    adversarial_weight: 0.001
    kl_weight: 0.000001
data:
  batch_size: 1
  downsample_factor: 0.25
  year: 2015
  wavelength: '171A'


trainer:
  max_epochs: 100
  device: 'cuda'
  log_every: 10
  checkpoint_path: ''
  log_path: 'refactor'
  accelerator: 'ddp'
