vae_gan:
  vae:
    channel_in: 1
    ch: 64
    blocks: [1, 2]
    latent_channels: 3
    num_res_blocks: 8
    norm_type: "gn"
    deep_model: False
    lr: 0.0001
  
  discriminator:
    in_channels: 1
    channel_list: [64, 128, 256]
    lr: 0.000001
  
  loss:
    perceptual_weight: 1.0
    l2_weight: 0.01
    adversarial_weight: 0.001
    kl_weight: 0.000001
data:
  batch_size: 8
  downsample_factor: 0.25
  bucket_name: 'sdo-subdataset'
  s3_key_train: 'dataset/train_dataset.pt'
  s3_key_val: 'dataset/val_dataset.pt'
  s3_key_test: 'dataset/test_dataset.pt'


trainer:
  max_epochs: 500
  accelerator: "gpu"
  devices: "auto"
  strategy: 'ddp_find_unused_parameters_true'
  precision: '16-mixed'

callbacks:
  checkpoint:
      dirpath: 'drive/MyDrive'               
      filename: 'epoch-{epoch:02d}'  
      save_top_k: -1          
      every_n_epochs: 5 

logger:
  project: 'your_project_name'




