vae_gan:
  vae:
    in_channels: 1
    latent_channels: 1
    channels: [64, 128, 256, 512]
    num_resblocks: 1 
    lr: 0.0001
  
  discriminator:
    in_channels: 1
    channel_list: [64, 128, 256]
    lr: 1e-6
  
  loss:
    perceptual_weight: 1.0
    l2_weight: 0.01
    adversarial_weight: 0.001
    kl_weight: 0.00006
data:
  batch_size: 4
  downsample_factor: 0.25


trainer:
  max_epochs: 100
  device: 'cpu'
  log_every: 5
  checkpoint_path: ''
  log_path: 'refactor\vae\checkpoints'
